version: '3.1'

services:
  sql_server:
    container_name: sql_server
    build: 
      context: .
      target: sql_server
    ports:
      - 1433:1433
    volumes:
      - ./mssql_data/:/var/opt/mssql/data/
    restart: always